[display]
label_width = 15 # default:15
green_until = 65 # default:65
orange_until = 85 # default:85

[display.options]
"system.gateway" = false
"system.dns" = false

[colors]
header = "#ea76cb"
title = "#8bd5ca"
label = "#c6a0f6"
user = "#f5a97f"
fqdn = "#eed49f"
dim = "#494d64"
active = "#a6da95"
inactive = "#ee99a0"
failed = "#ed8796"
green = "#a6da95"
orange = "#f5a97f"
red = "#ed8796"

[disks]
paths = ["/home"]

[services]
monitored = [
    "docker",
    "sshd",
    "doesnotexists"
    ]
